apiVersion: 1

datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      timeInterval: 15s
